### PR TITLE
Spelling and grammar

### PR DESCRIPTION
**Pull request by mteper**

### CODE REVIEW

**Comment by SajayAntony** [comment]
@muratg is there anything we need to do enable the CLA bot for this?

**Comment by muratg** [comment]
Yeah, @Eilon should be able to add the CLA bot to this repo.

**Comment by Eilon** [comment]
Yep, am planning to do that today.

**Comment by Eilon** [comment]
Leave a comment

**Comment by SajayAntony** [comment]
@mteper could you please rebase.

**Pull request closed without merging**
